image: anacha/arm32v7-alpine-qemu:latest

stages:
  - welcome

before_script:
  - uname -a

hello world CI/CD job:
  stage: welcome
  services:
    - docker:dind
  script:
    - cat /etc/alpine-release
    - echo 'Hello gitlab CI/CD, MeetingServer - 2nd'
