image: anacha/arm32v7-alpine-qemu:latest

stages:
  - welcome

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - uname -a

hello world CI/CD job:
  stage: welcome
  tags:
    - aarch64
    - alpine
  services:
    - docker:dind
  script:
    - cat /etc/alpine-release
    - echo 'Hello gitlab CI/CD, MeetingServer - 2nd'
